version: '2'
services:
  frps:
    image: registry.cn-hangzhou.aliyuncs.com/metahubs/yskj:frps0.44.0
    container_name:  frps
    volumes:
      - ./frp:/etc/frp/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    hostname: frps
    network_mode: host
