version: '2'
services:
  frpc:
    image: registry.cn-hangzhou.aliyuncs.com/metahubs/yskj:frpc
    container_name:  frpc
    volumes:
      - ./frp:/etc/frp/
    restart: always
    hostname: frpc
    network_mode: host
